spring:
  config:
    import: optional:file:./local.properties

  datasource:
    url: jdbc:postgresql://${RAILWAY_TCP_PROXY_DOMAIN}:${RAILWAY_TCP_PROXY_PORT}/${POSTGRES_DB}?sslmode=${SSL_MODE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    # By Default spring data opens 10 connections, increase as needed but 4 should be enough, saves memory
    # hikari:
    #   maximum-pool-size: 4
    #   minimum-idle: 1
    #   idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    sender_email: ${SMTP_SENDER_EMAIL}

  threads:
    virtual:
      enabled: true
  jmx:
    enabled: false
